### ISSUE TITLE
Consider to make the "Tartalomjegyzék" and "Cím" strings translation dependent

### ISSUE THREAD

**Issue by jano-wol** [anwolosz/synopsis#53]
The index page would be more harmonious this way. Currently it looks like this:
https://www.synopticus.org/hu/BT/index

**Comment by anwolosz** [comment]
These strings are actually not needed. Removed in https://github.com/anwolosz/synopsis/commit/fa42fd389eb6c87889322a2a1988cdf59232a235

**Comment by jano-wol** [comment]
I see that the "Cím" string was removed, but what about "Tartalomjegyzék"?
(The original feedback of RW was that "Tartalomjegyzék" looks weird with slavic translations.)

**Comment by anwolosz** [comment]
Sorry, I forgot about "Tartalomjegyzék"!
It is the exact copy of the string from the navbar. Just like in About, Sources, and Contact page. (So it is part of the language choice, and has nothing to do with the synopsis, or the language of the synopsis.)
I also can suggest to use the word "Index". Probably every language uses it because of the latin origins. In Synopsis Quattuor Evangeliorum they use the plural word: "Indices". I would prefer simple "Index".
Also an option to just remove the title string from the top of the content of the page.

What do you think? Ask rw too :)

**Comment by jano-wol** [comment]
All solutions are acceptable ofc, but here are our preferences:
RWs preferences: 1. no title; 2. current title; 3. index 
JWs preference: 1. index; 2. no title; 3. current solution
(1 is the most preferable, 3 is the least preferable)

**Comment by anwolosz** [comment]
For now "index" is the option we are moving on. Let's see if we like it or not :)
Done in : 984c7a31361172955f91495044054a6fd06da19a
