### ISSUE TITLE
KG Mt 5,48 "•" symbolt

### ISSUE THREAD

**Issue by anwolosz** [anwolosz/synopsis#73]
Is it a szentiras.hu API mistake, or the physical book contains it too? Is it has some kind of meaning I don't know about?

**Comment by jano-wol** [comment]
I think this is an API mistake. In the physical book Mt 5,48 is bolted, and it is starting with a commenting asterix * (these bolted commenting asterix are not rare in the KG bible, I think the problem here, is that the asterix is the first character of the verse.)
![1730753370512](https://github.com/user-attachments/assets/915b55dd-d956-483f-908a-95c6b466b602)

**Comment by anwolosz** [comment]
Done in: 36a2adba95089b196c4fe105791e82c91fa43f80
